name: CI Pipeline

on:
  push:
    branches:
      - feature/*
      - test
      - dev
      - prod
  pull_request:
    branches:
      - feature/*
      - test
      - dev
      - prod

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SPARK_JARS_PACKAGES: io.delta:delta-core_2.12:2.4.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyspark chispa pytest

    - name: Run unit tests
      run: |
        export PYTHONPATH=$(pwd)/src
        export PYSPARK_SUBMIT_ARGS="--packages io.delta:delta-core_2.12:2.4.0 pyspark-shell"
        python -m pytest tests/
